### PR TITLE
Added Gradle Building and Travis CI Support

### PR DESCRIPTION
**Pull request by keplersj**
With verbose commit messages at the request of @logomaster256

If you have any questions, comments, or concerns please be sure to voice them below or inline comments.

### CODE REVIEW

**Comment by viliml** [comment]
Did you check this?

**Comment by keplersj** [comment]
Just checked it out, the build file had some derpy syntax in it. I've fixed it.
I forgot to check it last night, sorry.

**Comment by mlazaric** [comment]
Errors again: https://travis-ci.org/KeplerGaming/KeplerCore/builds/15025549

**Comment by viliml** [comment]
https://travis-ci.org/KeplerGaming/KeplerCore/builds/15054362
Still errrors. Not related to derpy syntax

**Comment by mlazaric** [comment]
Merged to the gradle branch
Fixed with f7754db7cd7f35dc8efa7da7eacc0a64a6223c71

**Pull request closed without merging**
